language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coveralls flake8
  - pip install .

script:
  - flake8 .
  - coverage run --source=flask_utils setup.py test

after_success: coveralls

before_deploy:
  - git describe --dirty --always > VERSION

deploy:
  provider: pypi
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  skip_cleanup: true
  on:
    tags: true
